version: "2.1"

services:
  friend-management:
    image: friend-management
    container_name: friendmgt-app
    build:
          context: ./
          dockerfile: Dockerfile
    ports:
      - 8080:8080
